# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

services:
    app.folha.camara.service:
        class: AppBundle\Service\FolhaCamaraService
        arguments: ['@doctrine.orm.entity_manager']
